#!/bin/bash
# Quick reference for common tasks

echo "GNOME Text Extractor - Quick Commands"
echo "======================================"
echo ""
echo "Development:"
echo "  uv run python3 -m text_extractor.main    # Run the app"
echo "  uv sync                                   # Update dependencies"
echo "  uv pip list                               # List installed packages"
echo ""
echo "Testing:"
echo "  ./scripts/check-dist.sh                   # Validate distribution"
echo "  uv run python3 test_structure.py          # Test package structure"
echo ""
echo "Building Python Packages:"
echo "  ./scripts/build-dist.sh                   # Build Python packages (.tar.gz, .whl)"
echo "  ls -lh dist/                              # View built packages"
echo ""
echo "Building .deb Package:"
echo "  ./scripts/build-deb.sh                    # Build Debian package"
echo "  ./scripts/test-deb.sh                     # Test .deb package"
echo "  sudo dpkg -i dist/deb/*.deb               # Install .deb locally"
echo "  sudo apt remove gnome-text-extractor      # Uninstall"
echo ""
echo "Installation:"
echo "  ./install/install.sh                      # Install from source"
echo "  text-extractor                            # Run installed app"
echo ""
echo "Git/Release:"
echo "  git status                                # Check changes"
echo "  git add .                                 # Stage all changes"
echo "  git commit -m 'message'                   # Commit changes"
echo "  git push origin master                    # Push to GitHub"
echo "  git tag -a v1.0.0 -m 'Release 1.0.0'     # Create release tag"
echo "  git push origin v1.0.0                    # Push tag (auto-builds Python + .deb)"
echo ""
echo "Documentation:"
echo "  cat README.md                             # User guide"
echo "  cat DEB_DISTRIBUTION.md                   # .deb package guide"
echo "  cat DEBIAN_PACKAGING.md                   # Detailed packaging info"
echo "  cat DISTRIBUTION.md                       # General distribution"
echo ""
