name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper dh-python python3-all python3-setuptools python3-pip dpkg-dev pybuild-plugin-pyproject python3-hatchling
    
    - name: Build Python packages
      run: python -m build
    
    - name: Build .deb package
      run: |
        chmod +x debian/rules
        dpkg-buildpackage -us -uc -b || echo "Warning: .deb build failed, continuing with Python packages only"
        mkdir -p dist/deb
        mv ../*.deb dist/deb/ 2>/dev/null || true
        mv ../*.changes dist/deb/ 2>/dev/null || true
        mv ../*.buildinfo dist/deb/ 2>/dev/null || true
        ls -la dist/
        ls -la dist/deb/ || true
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.tar.gz
          dist/*.whl
          dist/deb/*.deb
        generate_release_notes: true
        fail_on_unmatched_files: false
